// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC29C80tp6AOlb0eR4X0Ad7bIk5yON309U',
    appId: '1:65672822021:web:c5cd1760f929d049ae8b6c',
    messagingSenderId: '65672822021',
    projectId: 'settleupp-958f1',
    authDomain: 'settleupp-958f1.firebaseapp.com',
    storageBucket: 'settleupp-958f1.firebasestorage.app',
    measurementId: 'G-G5Z14DXB6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_LeGJ1n6yeIZui3ZBjHZBtt8Q7RPud-U',
    appId: '1:65672822021:android:74d144f9bcef98edae8b6c',
    messagingSenderId: '65672822021',
    projectId: 'settleupp-958f1',
    storageBucket: 'settleupp-958f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBR39PrBjLKV1qlMqxWWUpe_jo72HZe4',
    appId: '1:65672822021:ios:b244ed9b10806159ae8b6c',
    messagingSenderId: '65672822021',
    projectId: 'settleupp-958f1',
    storageBucket: 'settleupp-958f1.firebasestorage.app',
    iosBundleId: 'com.example.settleupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPBR39PrBjLKV1qlMqxWWUpe_jo72HZe4',
    appId: '1:65672822021:ios:b244ed9b10806159ae8b6c',
    messagingSenderId: '65672822021',
    projectId: 'settleupp-958f1',
    storageBucket: 'settleupp-958f1.firebasestorage.app',
    iosBundleId: 'com.example.settleupApp',
  );
}
